# fly.toml app configuration file generated for core-fly on 2023-05-30T10:51:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "core-fly"
primary_region = "cdg"
